/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import entidades.Autor;
import entidades.Libro;
import entidades.LibroElectronico;
import entidades.LibroImpreso;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import operaciones.OperacionesLibro;
import operaciones.Validaciones;

public class JFrameNuevoLibro extends javax.swing.JFrame {
    OperacionesLibro oper;
    Validaciones val;
    
    public JFrameNuevoLibro() {
        initComponents();
        jPanelImpreso.setVisible(true);
        jPanelElectronico.setVisible(false);
        jTextFieldInteractivo.setEnabled(false);
        
        oper=new OperacionesLibro();
        
        jRadioButtonPastaDura.setSelected(true);
        jComboBoxTipo.setSelectedIndex(1);
        
        val=new Validaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoPasta = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIsbn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerNumPaginas = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxAutor = new javax.swing.JComboBox<>();
        jPanelImpreso = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonPastaDura = new javax.swing.JRadioButton();
        jRadioButtonPastaSuave = new javax.swing.JRadioButton();
        jLabelPastaSeleccionada = new javax.swing.JLabel();
        jPanelElectronico = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerTamanioArchivo = new javax.swing.JSpinner();
        jCheckBoxEsInteractivo = new javax.swing.JCheckBox();
        jTextFieldInteractivo = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tipo:");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Impreso", "Electronico" }));
        jComboBoxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoItemStateChanged(evt);
            }
        });

        jLabel2.setText("ISBN:");

        jTextFieldIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIsbnActionPerformed(evt);
            }
        });
        jTextFieldIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIsbnKeyTyped(evt);
            }
        });

        jLabel3.setText("Titulo:");

        jTextFieldTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTituloKeyTyped(evt);
            }
        });

        jLabel4.setText("Autor Principal: ");

        jSpinnerNumPaginas.setModel(new javax.swing.SpinnerNumberModel(10, 10, 1000, 1));

        jLabel5.setText("Numero de Paginas: ");

        jComboBoxAutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autor 1", "Autor 2", "Autor 3", "Autor 4" }));
        jComboBoxAutor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAutorItemStateChanged(evt);
            }
        });

        jPanelImpreso.setBackground(new java.awt.Color(204, 255, 204));
        jPanelImpreso.setBorder(javax.swing.BorderFactory.createTitledBorder("Libro Impreso"));

        jLabel6.setText("Tipo de Pasta:");

        buttonGroupTipoPasta.add(jRadioButtonPastaDura);
        jRadioButtonPastaDura.setText("Dura");
        jRadioButtonPastaDura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonPastaDuraStateChanged(evt);
            }
        });

        buttonGroupTipoPasta.add(jRadioButtonPastaSuave);
        jRadioButtonPastaSuave.setText("Suave");
        jRadioButtonPastaSuave.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonPastaSuaveStateChanged(evt);
            }
        });

        jLabelPastaSeleccionada.setText("jLabel8");

        javax.swing.GroupLayout jPanelImpresoLayout = new javax.swing.GroupLayout(jPanelImpreso);
        jPanelImpreso.setLayout(jPanelImpresoLayout);
        jPanelImpresoLayout.setHorizontalGroup(
            jPanelImpresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImpresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelImpresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelImpresoLayout.createSequentialGroup()
                        .addComponent(jRadioButtonPastaDura)
                        .addGap(17, 17, 17)
                        .addComponent(jRadioButtonPastaSuave)
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(jPanelImpresoLayout.createSequentialGroup()
                        .addComponent(jLabelPastaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelImpresoLayout.setVerticalGroup(
            jPanelImpresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImpresoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelImpresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButtonPastaDura)
                    .addComponent(jRadioButtonPastaSuave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabelPastaSeleccionada))
        );

        jPanelElectronico.setBackground(new java.awt.Color(255, 102, 102));
        jPanelElectronico.setBorder(javax.swing.BorderFactory.createTitledBorder("Libro Electronico"));

        jLabel7.setText("Tamano del archivo:");

        jSpinnerTamanioArchivo.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.5f), Float.valueOf(0.3f), Float.valueOf(100.0f), Float.valueOf(0.5f)));

        jCheckBoxEsInteractivo.setText("Es interactivo?");
        jCheckBoxEsInteractivo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxEsInteractivoStateChanged(evt);
            }
        });

        jTextFieldInteractivo.setText("nada");

        javax.swing.GroupLayout jPanelElectronicoLayout = new javax.swing.GroupLayout(jPanelElectronico);
        jPanelElectronico.setLayout(jPanelElectronicoLayout);
        jPanelElectronicoLayout.setHorizontalGroup(
            jPanelElectronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelElectronicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelElectronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jCheckBoxEsInteractivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelElectronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelElectronicoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldInteractivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSpinnerTamanioArchivo))
                .addContainerGap())
        );
        jPanelElectronicoLayout.setVerticalGroup(
            jPanelElectronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelElectronicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelElectronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinnerTamanioArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelElectronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxEsInteractivo)
                    .addComponent(jTextFieldInteractivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelImpreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxAutor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButtonGuardar)
                .addGap(45, 45, 45)
                .addComponent(jButtonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelImpreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoItemStateChanged
        int indiceSeleccionado = 
                jComboBoxTipo.getSelectedIndex();
        if(indiceSeleccionado==0){//libro impreso
            jPanelImpreso.setVisible(true);
            jPanelElectronico.setVisible(false);
        }else{// libro electronico
               jPanelImpreso.setVisible(false);
            jPanelElectronico.setVisible(true);
        
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoItemStateChanged

    private void jRadioButtonPastaDuraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonPastaDuraStateChanged
            if(jRadioButtonPastaDura.isSelected()){
                jLabelPastaSeleccionada.setText(
                        jRadioButtonPastaDura.getText());
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPastaDuraStateChanged

    private void jRadioButtonPastaSuaveStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonPastaSuaveStateChanged
        if(jRadioButtonPastaSuave.isSelected()){
            jLabelPastaSeleccionada.setText(
            jRadioButtonPastaSuave.getText());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPastaSuaveStateChanged

    private void jCheckBoxEsInteractivoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxEsInteractivoStateChanged
            if(jCheckBoxEsInteractivo.isSelected()){
                jTextFieldInteractivo.setEnabled(true);
            }else{
                jTextFieldInteractivo.setText("");
                jTextFieldInteractivo.setEnabled(false);
                
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEsInteractivoStateChanged

    private void jButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseClicked
        this.guardarLibro();        
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarMouseClicked
    
    //int contCaracteres=0;
    private void jTextFieldIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIsbnKeyTyped
        Character ch = evt.getKeyChar();
        if(!Character.isDigit(ch) && ch != KeyEvent.VK_BACK_SPACE  && ch != KeyEvent.VK_DELETE  ){
            JOptionPane.showMessageDialog(this, "solo numeros");
            evt.consume(); //consume el evento, por tanto
            //la tecla ya no se tipea (no se dibuja)
        }/*else{//si es digito
         if(contCaracteres>=13){
                 JOptionPane.showMessageDialog(this, "solo 13 numeros");
                  evt.consume();
            }else{
                    contCaracteres++;} */
      
         //verificacion de cantidad de caracteres en base a longitud del texto
        if(jTextFieldIsbn.getText().length()>=13){
              JOptionPane.showMessageDialog(this, "solo 13 numeros");
              evt.consume();
        }
       
// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIsbnKeyTyped

    private void jTextFieldTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTituloKeyTyped
        boolean res = val.soloLetras(evt.getKeyChar());
        if(!res){
            JOptionPane.showMessageDialog(this, "solo letras");
            evt.consume();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloKeyTyped

    private void jTextFieldIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIsbnActionPerformed

    private void jComboBoxAutorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAutorItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAutorItemStateChanged

    public void guardarLibro(){
        //1. verificaciones y validaciones
        if(jTextFieldIsbn.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese isbn");
            return;
        }
        //2. leer datos del formulario
        String isbn = jTextFieldIsbn.getText();
        String tit = jTextFieldTitulo.getText();
        int np = (int)jSpinnerNumPaginas.getValue();
        String autor= (String)jComboBoxAutor.getSelectedItem();
        Autor au = new Autor();
        au.setNombres(autor);
        int tipo = jComboBoxTipo.getSelectedIndex();
        Libro libro ;
      if(tipo ==0){//libro impreso
          String tipoPasta ="";
          if(jRadioButtonPastaDura.isSelected()){
              tipoPasta=jRadioButtonPastaDura.getText();
          }else if(jRadioButtonPastaSuave.isSelected()){
              tipoPasta = jRadioButtonPastaSuave.getText();
          }
          libro = new LibroImpreso(np, 
                  tipoPasta, isbn, tit, 2019, 0, au);
      }else if(tipo==1){// libro electronico
          float tamanio = (float)jSpinnerTamanioArchivo.getValue();
          boolean isInteractivo = jCheckBoxEsInteractivo.isSelected();
          String textInteractivo="";
          if(isInteractivo){
              textInteractivo= jTextFieldInteractivo.getText();
          }
          libro = new LibroElectronico(tamanio, isInteractivo,
                  isbn, tit, np, 0, au);
      } else{
          libro = new LibroImpreso();
      } 
       double precio = libro.calcularPrecio();
         JOptionPane.showMessageDialog(this, 
               "El libro" + libro.toString());
       JOptionPane.showMessageDialog(this, 
               "El precio del libro es" + precio);
       //guardar en la coleccion
       oper.agregar(libro);
       oper.guardarEnArchivo(libro);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameNuevoLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipoPasta;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JCheckBox jCheckBoxEsInteractivo;
    private javax.swing.JComboBox<String> jComboBoxAutor;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelPastaSeleccionada;
    private javax.swing.JPanel jPanelElectronico;
    private javax.swing.JPanel jPanelImpreso;
    private javax.swing.JRadioButton jRadioButtonPastaDura;
    private javax.swing.JRadioButton jRadioButtonPastaSuave;
    private javax.swing.JSpinner jSpinnerNumPaginas;
    private javax.swing.JSpinner jSpinnerTamanioArchivo;
    private javax.swing.JTextField jTextFieldInteractivo;
    private javax.swing.JTextField jTextFieldIsbn;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
